config/routes.rb
Rails.application.routes.draw do
 root 'static_pages#index'
get '/about', to: 'static_pages#about', as: :about
get '/education', to: 'static_pages#education', as: :education
get '/work_history', to: 'static_pages#work_history', as: :work_history

 resources :static_pages #this is pointing to the static_pages controller
 

end

app/models/education.rb
class Education < ActiveRecord::Base
end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end

  def work_history
    @work = Work.all
  end

  def education
    @education = Education.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav_bar.html.erb
<%= link_to 'Home', root_path %> |
<%= link_to 'About', about_path %> |
<%= link_to 'Education', education_path %> |
<%= link_to 'Work History', work_history_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BraydenGreen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<%= render partial: 'layouts/nav_bar' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>Brayden Green</h1>

app/views/static_pages/education.html.erb
<h1>Brayden Green</h1>
<h2>Education</h2>
<% @education.each do |i| %>
<ul>
  <li>School Name: <%= i.school_name %></li>
  <li>Start Date: <%= i.start_date %></li>
  <li>End Date: <%= i.end_date %></li>
  <li>Liked? <%= i.liked %></li>
  </ul>
 <% end %>

app/views/static_pages/index.html.erb
<h1>Brayden Green</h1>
<h2>The Man, The Myth, The Legend</h2>

app/views/static_pages/work_history.html.erb
<h1>Brayden Green</h1>
<h2>Work History</h2>

<% @work.each do |i| %>
<ul>
  <li>Title: <%= i.job_title %></li>
  <li>Employer: <%= i.employer %></li>
  <li>Start Date: <%= i.start_date %></li>
  <li>End Date: <%= i.end_date %></li>
  <li>Liked? <%= i.liked %></li>
  </ul>
 <% end %>